#!/bin/bash

# This script guides you through setting up OAuth providers in Supabase for the HSE Workflow project

echo "Setting up OAuth providers for Supabase project: hse_wkflow (tjwntuutssejybhpdnbe)"
echo "--------------------------------------------------------------------"
echo "To enable OAuth providers, follow these steps:"
echo ""
echo "1. Go to https://supabase.com/dashboard/project/tjwntuutssejybhpdnbe/auth/providers"
echo "2. Enable and configure the following providers:"
echo "   - Email (already enabled by default)"
echo "   - Google"
echo "   - GitHub"
echo ""
echo "For Google OAuth:"
echo "  - Create a Google Cloud project: https://console.cloud.google.com/projectcreate"
echo "  - Set up OAuth consent screen"
echo "  - Create OAuth client ID credentials"
echo "  - Add authorized redirect URI: https://tjwntuutssejybhpdnbe.supabase.co/auth/v1/callback"
echo ""
echo "For GitHub OAuth:"
echo "  - Go to GitHub Developer settings: https://github.com/settings/developers"
echo "  - Create a new OAuth App"
echo "  - Add Homepage URL: https://tjwntuutssejybhpdnbe.supabase.co"
echo "  - Add Authorization callback URL: https://tjwntuutssejybhpdnbe.supabase.co/auth/v1/callback"
echo ""
echo "After configuring these providers, the application will automatically use them for authentication."