// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjwntuutssejybhpdnbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqd250dXV0c3NlanliaHBkbmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDU3NTksImV4cCI6MjA3MzIyMTc1OX0.iqqvanvFR8YBNxlnjGHoh-EpNEkbg9lpgAei-I0BZbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});